baseURL = "https://archive.thatfullpocket.com/"
title = "Full Pocket"
theme ="hugo-theme-minos"
languageCode = "en-us"
enableEmoji = true
copyright = "© 2019 Made by <a href='https://twitter.com/jkirsteins'>@jkirsteins</a>."
googleAnalytics = "UA-151678519-1"

[author]
  name = "Jānis Kiršteins"

[menu]

  [[menu.main]]
    name="About"
    url="/about"

  [[menu.main]]
    name="Archive"
    url="/post"

  [[menu.main]]
    name = "Content on GitHub"
    pre = '<i class="fab fa-github"></i>'
    url = "https://www.github.com/kirsis/fullpocket"

  [[menu.main]]
    name = "Twitter"
    pre = '<i class="fab fa-twitter"></i>'
    url = "https://www.twitter.com/thatfullpocket"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  titleEmoji = ":chart_with_upwards_trend:"
  # change this!
  twitter = "jkirsteins"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "archive"
  url = "post/"

[[params.menu]]
  name = "about"
  url = "about/"


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true
